;this file was generated by Typing_Aid_everywhere_multi_clone.ahk 
g_lineNumberFeedback=Typing_Aid_everywhere_multi_clone.ahk~~406 token363 
#SingleInstance, force 
#NoTrayIcon 
global g_doSaveLogFiles 
global g_doRunLogFiles 
g_doSaveLogFiles := 0 
g_doRunLogFiles := 0 
SetTitleMatchMode, 1
activeTitle := RegExReplace(activeTitle, Chr(37) . ".*", "") ; delete prozent. should be easy to include variable later. some websites have suche long title with the procent in it. dont like it. simplify it. 16.03.2017
global g_lineNumberFeedback
g_lineNumberFeedback=G:\fre\git\github\2\Source\Typing_Aid_everywhere_multi_clone.ahk~~390
ActionListDir = .\..\ActionLists\ChromeWidgetWin1
activeTitle = G:\downloads\gi-18-10-29_10-08\gi
activeClass = ChromeWidgetWin1
ActionListNEW = G:\downloads\gi-18-10-29_10-08\gi 
ActionListFilterPath2 = .\..\ActionLists\ChromeWidgetWin1\ActionListNameFilter.inc.ahk 
ActionListFilterPath2Abs = G:\fre\git\github\2\Source\..\ActionLists\ChromeWidgetWin1\ActionListNameFilter.inc.ahk 
fileEx := FileExist ( ActionListFilterPath2Abs ) 
if( !fileEx ) { 
message = :(  `n '%ActionListFilterPath2%'  `n '%ActionListFilterPath2Abs%'  `n existiert nicht ( %fileEx% = fileEx ) . `n `n message with id (1704171514) was copied to the Clipboard. Sor you probably could find this source code little bit easier. `n (from: %A_LineFile%~%A_LineNumber%) 
 tooltip, %message% 
 Clipboard = %message%  
 Msgbox,4 , :( ActionListNameFilter.inc.ahk not found , %message% , 4  
 Sleep, 4000 
ExitApp  
} 
#Include *i G:\fre\git\github\2\Source\..\ActionLists\ChromeWidgetWin1\ActionListNameFilter.inc.ahk  ; thats the subfolder  wordlost inside class 
varInjects1 := mvarInjects(ActionListDir, ActionListNEW, activeClass, activeTitle) 
ActionListOLD = G:\downloads\gi-18-10-29_10-08 
gi_everywhereSourcePath =  
ActionListActive  =  

TargetScriptTitle = gi-everywhere - Active ahk_class AutoHotkey
stringToSend := (InStr(ActionListNEW,"\")) ? ActionListNEW : ActionListDir . "\" . ActionListNEW
; result := Send_WM_COPYDATA(stringToSend, TargetScriptTitle)
if(false){  ; temporaly deactivated . for compatibiliti thinks 02.03.2018 17:10
    try{
        y := ComObjActive("{93C04B39-0465-4460-8CA0-7BFFF481FF98}")
        y.callFunction( "Receive_ActionListAddress", stringToSend ) ;will call the function of the other script
    } catch e{
        tip:="Exception:`n" e.What "`n" e.Message "`n" e.File "@" e.Line
        tooltip, % tip
}}
if(true){  ; old scool. for compatibiliti thinks 02.03.2018 17:10

    RegWrite, REG_SZ, HKEY_CURRENT_USER, SOFTWARE\sl5net, ActionListDir, %ActionListDir%
    RegWrite, REG_SZ, HKEY_CURRENT_USER, SOFTWARE\sl5net, ActionListActive, %ActionListActive%
    RegWrite, REG_SZ, HKEY_CURRENT_USER, SOFTWARE\sl5net, ActionListNEW, %ActionListNEW%
    RegWrite, REG_SZ, HKEY_CURRENT_USER, SOFTWARE\sl5net, ActionListNEWarchivePath, %ActionListNEWarchivePath%

    ActionList = %ActionListDir%\%ActionListNEW%

    ActionList := removesSymbolicLinksFromFileAdress(ActionList)
if(0){
    ; ActionList = %ActionListNEWarchivePath% ; its not existing here 03.03.2018 19:13
    ; msgbox,%ActionListNEWarchivePath%
    pLength := 0
    while(pLength <> StrLen(ActionList )){
        ; tooltip,% A_index . "# Line:" . A_LineNumber . " Name:" . A_ScriptName . " "
        pLength := StrLen(ActionList )
        ActionList := RegExReplace(ActionList ,"(\\[^\\]+\\\.\.)+") ; works. removes all symbolic links 24.02.2018  cleanPath
    }
    ActionList := RegExReplace(ActionList,"\\\.\\")  ; works. removes all symbolic link 24.02.2018 cleanPath
    ActionList := RegExReplace(ActionList,"^\.\\")  ; works. removes all symbolic link 24.02.2018  cleanPath
}
    ;msgbox,% ActionList
    FileRead, fileContent, % ActionList
    ; StringReplace, fileContent, fileContent, ..\ActionLists, .. \
    l1 := StrLen(fileContent)
    fileContent := StrReplace(fileContent, "..\ActionLists\", "..\" ) ; https://ahkde.github.io/docs/commands/StringReplace.htm
l2 := StrLen(fileContent)
if(1 && l1 > l2){ ; proof it test it
    FileSave(fileContent, ActionList )
    if(1 && InStr(A_ComputerName,"SL5"))
        msgbox,% ActionList " 12is saved (l1 > l2) (G:\fre\git\github\2\Source\Typing_Aid_everywhere_multi_clone.ahk~447) (" RegExReplace(A_LineFile,".*\\") "~" A_LineNumber ") ---- " fileContent
    tooltip,% ActionList " 12is saved (l1 > l2) (G:\fre\git\github\2\Source\Typing_Aid_everywhere_multi_clone.ahk~447) (" RegExReplace(A_LineFile,".*\\") "~" A_LineNumber ") ---- " fileContent
}


;

if(1){
    ; dirty bug fix ._Generated.txt 04.03.2018 10:44
    If(FileExist( ActionList . "._Generated.ahk")) ; dirty bugFix TODO: prettyFy it
      ActionList .= "._Generated.ahk"

  ; msgbox, % ActionList
}
    if(!RegExMatch(ActionList,"created_token_17-08-10_16-17")) ; todo: whey control here? wrong place. quck dirty 25.03.2018 01:36
        RegWrite, REG_SZ, HKEY_CURRENT_USER, SOFTWARE\sl5net, ActionList, %ActionList% ; old scool. for compatibiliti thinks 02.03.2018 17:10

}
 ActionListNEWactivate( ActionListDir , ActionListNEW, ActionListActive, gi_everywhereSourcePath, activeClass , activeTitle) 
varInjects2 := mvarInjects(ActionListDir, ActionListNEW, activeClass, activeTitle) 
ExitApp 
#Include, inc_ahk\\Typing_Aid_everywhere_multi_clone.inc.ahk  ; 
