;this file was generated by C:\temp\global-IntelliSense-everywhere-master\Source\Typing_Aid_everywhere_multi_clone.ahk 
g_lineNumberFeedback=Typing_Aid_everywhere_multi_clone.ahk~~365 token363 
#SingleInstance, force 
#NoTrayIcon 
global g_doSaveLogFiles 
global g_doRunLogFiles 
g_doSaveLogFiles := 0 
g_doRunLogFiles := 0 
SetTitleMatchMode, 1
activeTitle := RegExReplace(activeTitle, "%.*", "") ; should be easy to include variable later. some websites have suche long title with the procent in it. dont like it. simplify it. 16.03.2017 18:39
activeTitle := RegExReplace(activeTitle, "`%.*", "") ; should be easy to include variable later. some websites have suche long title with the procent in it. dont like it. simplify it. 16.03.2017 18:39
if( false && A_ScriptName == "temp.ahk") {
global g_lineNumberFeedback
 g_lineNumberFeedback=Typing_Aid_everywhere_multi_clone.ahk~~340
   wordlistDir = Wordlists\FunnyWidgetHuHu
   activeTitle = lustiger landkaese
   activeClass = FunnyWidgetHuHu
} else {
global g_lineNumberFeedback
 g_lineNumberFeedback=Typing_Aid_everywhere_multi_clone.ahk~~340
   wordlistDir = .\..\Wordlists\_globalWordListsGenerated
   activeTitle = _global
   activeClass = _globalWordListsGenerated
   wordlistNEW = _global
} 
wordlistFilterPath2 = .\..\Wordlists\_globalWordListsGenerated\wordlistNameFilter.inc.ahk 
wordlistFilterPath2Abs = C:\temp\global-IntelliSense-everywhere-master\Source\..\Wordlists\_globalWordListsGenerated\wordlistNameFilter.inc.ahk 
fileEx := FileExist ( wordlistFilterPath2Abs ) 
if( !fileEx ) { 
message = :(  `n '%wordlistFilterPath2%'  `n '%wordlistFilterPath2Abs%'  `n existiert nicht ( %fileEx% = fileEx ) . `n `n message with id (1704171514) was copied to the Clipboard. Sor you probably could find this source code little bit easier. `n (from: %A_ScriptName%~%A_LineNumber%) 
 tooltip, %message% 
 Clipboard = %message%  
 Msgbox,4 , :( wordlistNameFilter.inc.ahk not found , %message% , 4  
 Sleep, 4000 
ExitApp  
} 
#Include *i C:\temp\global-IntelliSense-everywhere-master\Source\..\Wordlists\_globalWordListsGenerated\wordlistNameFilter.inc.ahk  ; thats the subfolder  wordlost inside class 
varInjects1 := mvarInjects(wordlistDir, wordlistNEW, activeClass, activeTitle) 
wordlistOLD =  
typingAidSourcePath = \ 
wordlistActive  = wordlist.txt 
wordlistOLDbackup( wordlistDir , wordlistOLD) 
wordlistOLDdisable( typingAidSourcePath, wordlistActive ) 
wordlistNEWactivate( wordlistDir , wordlistNEW, wordlistActive, typingAidSourcePath, activeClass , activeTitle) 
varInjects2 := mvarInjects(wordlistDir, wordlistNEW, activeClass, activeTitle) 
ExitApp 
#Include, inc_ahk\\Typing_Aid_everywhere_multi_clone.inc.ahk  ; 
