;this file was generated by Typing_Aid_everywhere_multi_clone.ahk 
g_lineNumberFeedback=Typing_Aid_everywhere_multi_clone.ahk~~530 token363 
#SingleInstance, force 
#NoTrayIcon 
global g_doSaveLogFiles 
global g_doRunLogFiles 
g_doSaveLogFiles := 0 
g_doRunLogFiles := 0 
SetTitleMatchMode, 1
activeTitle := RegExReplace(activeTitle, Chr(37) . ".*", "") ; delete prozent. should be easy to include variable later. some websites have suche long title with the procent in it. dont like it. simplify it. 16.03.2017
global g_lineNumberFeedback
g_lineNumberFeedback=513~G:\fre\git\github\2\Source\Typing_Aid_everywhere_multi_clone.ahk~
actionListDir = .\..\actionLists\_globalActionListsGenerated
activeTitle = isNotAProject
activeClass = _globalActionListsGenerated
actionListNEW = isNotAProject 
actionListFilterPath2 = .\..\actionLists\_globalActionListsGenerated\actionListNameFilter.inc.ahk 
actionListFilterPath2Abs = G:\fre\git\github\2\Source\..\actionLists\_globalActionListsGenerated\actionListNameFilter.inc.ahk 
fileEx := FileExist ( actionListFilterPath2Abs ) 
if( !fileEx ) { 
message = :(  `n '%actionListFilterPath2%'  `n '%actionListFilterPath2Abs%'  `n existiert nicht ( %fileEx% = fileEx ) . `n `n message with id (1704171514) was copied to the Clipboard. Sor you probably could find this source code little bit easier. `n (from: %A_LineFile%~%A_LineNumber%) 
 tooltip, %message%=m , 1,1 
 Sleep, 4000 
ExitApp  
} 
#Include *i G:\fre\git\github\2\Source\..\actionLists\_globalActionListsGenerated\actionListNameFilter.inc.ahk  ; thats the subfolder  wordlost inside class 
varInjects1 := mvarInjects(actionListDir, actionListNEW, activeClass, activeTitle) 
actionListOLD = global-IntelliSense-everywhere-Nightly-Build [G:\fre\git\github\global-IntelliSense-everywhere-Nightly-Build] - ...\Source\config\config.inc.ahk [global-IntelliSense-everywhere-Nightly-Build] - IntelliJ IDEA (Administrator) 
gi_everywhereSourcePath =  
actionListActive  =  

TargetScriptTitle = gi-everywhere - Active ahk_class AutoHotkey
stringToSend := (InStr(actionListNEW,"\")) ? actionListNEW : actionListDir . "\" . actionListNEW
; result := Send_WM_COPYDATA(stringToSend, TargetScriptTitle)
if(false){  ; temporaly deactivated . for compatibiliti thinks 02.03.2018 17:10
    try{
        y := ComObjActive("{93C04B39-0465-4460-8CA0-7BFFF481FF98}")
        y.callFunction( "Receive_actionListAddress", stringToSend ) ;will call the function of the other script
    } catch e{
        tip:="Exception:`n" e.What "`n" e.Message "`n" e.File "@" e.Line
        tooltip, % tip
}}
if(true){  ; old scool. for compatibiliti thinks 02.03.2018 17:10

    RegWrite, REG_SZ, HKEY_CURRENT_USER, SOFTWARE\sl5net\gi, actionListDir, %actionListDir%
    RegWrite, REG_SZ, HKEY_CURRENT_USER, SOFTWARE\sl5net\gi, actionListActive, %actionListActive%
    RegWrite, REG_SZ, HKEY_CURRENT_USER, SOFTWARE\sl5net\gi, actionListNEW, %actionListNEW%
    RegWrite, REG_SZ, HKEY_CURRENT_USER, SOFTWARE\sl5net\gi, actionListNEWarchivePath, %actionListNEWarchivePath%

    actionList = %actionListDir%\%actionListNEW%

    actionList := removesSymbolicLinksFromFileAdress(actionList)

    if( SubStr( actionList , -3 ) <> ".ahk" ) ; 07.11.2018 22:05
        actionList .= ".ahk"

; hallo hllk

if(0){
    ; actionList = %actionListNEWarchivePath% ; its not existing here 03.03.2018 19:13
    ; msgbox,%actionListNEWarchivePath%
    pLength := 0
    while(pLength <> StrLen(actionList )){
        ; tooltip,% A_index "# Line:" A_LineNumber " Name:" A_ScriptName " "
        pLength := StrLen(actionList )
        actionList := RegExReplace(actionList ,"(\\[^\\]+\\\.\.)+") ; works. removes all symbolic links 24.02.2018  cleanPath
    }
    actionList := RegExReplace(actionList,"\\\.\\")  ; works. removes all symbolic link 24.02.2018 cleanPath
    actionList := RegExReplace(actionList,"^\.\\")  ; works. removes all symbolic link 24.02.2018  cleanPath
}
    ;msgbox,% actionList
    FileRead, fileContent, % actionList
    ; StringReplace, fileContent, fileContent, ..\actionLists, .. \
    l1 := StrLen(fileContent)
    fileContent := StrReplace(fileContent, "..\actionLists\", "..\" ) ; https://ahkde.github.io/docs/commands/StringReplace.htm
l2 := StrLen(fileContent)
if(1 && l1 > l2){ ; proof it test it
    FileSave(fileContent, actionList )
    if(1 && InStr(A_ComputerName,"SL5"))
        msgbox,% actionList " 12is saved (l1 > l2) (G:\fre\git\github\2\Source\Typing_Aid_everywhere_multi_clone.ahk~585) (" RegExReplace(A_LineFile,".*\\") "~" A_LineNumber ") ---- " fileContent
    tooltip,% actionList " 12is saved (l1 > l2) (G:\fre\git\github\2\Source\Typing_Aid_everywhere_multi_clone.ahk~585) (" RegExReplace(A_LineFile,".*\\") "~" A_LineNumber ") ---- " fileContent
}

if(0){ ; diesabled 24.12.2018 13:36 ... so its not possible to update lists without icludes
    ; inside of : while(true)
    ; dirty bug fix ._Generated.txt 04.03.2018 10:44

    postFixGenerated := "._Generated.ahk"
    actionListPostFix  := SubStr(rtrim(actionList), - StrLen(postFixGenerated) + 1 ) ; That works I've tested it 01.11.2018 14:59
    itsAGeneratedList := ( postFixGenerated == actionListPostFix )

    If(!itsAGeneratedList && !FileExist( actionList "._Generated.ahk")) ; dirty bugFix TODO: prettyFy it
    {
      actionList .= "._Generated.ahk" ; inside the while(true)
      tooltip, token=1812241329 (from: %A_LineFile%~%A_LineNumber%)
      sleep,3000
    }
  ; msgbox, % actionList
}
    if(1 && !RegExMatch(actionList,"created_token_17-08-10_16-17")) ; todo: whey control here? wrong place. quck dirty 25.03.2018 01:36
        setRegistry_actionList( actionList ) ; old scool. for compatibiliti thinks 02.03.2018 17:10)

    RegRead, CreatedDir, HKEY_CURRENT_USER, SOFTWARE\sl5net\gi, CreatedDir
    if(CreatedDir){
        RegWrite, REG_SZ, HKEY_CURRENT_USER, SOFTWARE\sl5net\gi, CreatedDir, % "" ; RegWrite , RegSave , Registry
        actionListOpen := StrReplace(actionList, "._Generated.ahk")
        openInEditorFromIntern( actionListOpen )
    }
#Include,RegWrite181031.ahk
}
 actionListNEWactivate( actionListDir , actionListNEW, actionListActive, gi_everywhereSourcePath, activeClass , activeTitle) 
varInjects2 := mvarInjects(actionListDir, actionListNEW, activeClass, activeTitle) 
ExitApp 
#Include, inc_ahk\\Typing_Aid_everywhere_multi_clone.inc.ahk  ; 
